# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3196e80e3b392e153d572a03a7f1446e74316938c8857e2be6ac6347f507a8b4495cd4dc787a0f98529b1ef9026998eaef05558a1de0a2c0b2a655acbd17b6e

test:
  secret_key_base: 87fbacac094b01fb0d8676c19348ed73984cf16c183ca51207694ca41ba5b67e9a6b2e0381c4a32f2b10404b762f2e32c70ac7a612f58cf22d2d1fa29fdc1b08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
